Controllers films users
anastasiaelis/java-filmorate pull request #6
Opened 2024-02-11 17:32 UTC by anastasiaelis

первое ревью

2024-02-12 06:20 UTC, VadimZharkov reviewed
На данный момент валидация проводится как с помощью аннотаций так и в методах класса Validator. Не нужно дублировать проверки и там и там.
Например,
```
        if (!user.getEmail().contains("@")) {
            log.error("Email пользователя пуст или не содержит @");
            throw new ValidationException("Email должен содержать @ и не быть пустым");
        }
```
такая проверка уже зашита в
@Email
и поэтому в методе уже избыточна

2024-02-12 06:23 UTC, VadimZharkov requested changes
Можно улучшить

2024-02-12 17:07 UTC, anastasiaelis commented
Можно я пока так оставлю, в след.спринте сделаю, с аннотациями?

2024-02-13 06:09 UTC, VadimZharkov requested changes
Хорошо оставляем текущую реализацию, но нужно чтобы все  автоматизированные проверки в гите проходили как минимум. Сейчас они красные.

2024-02-14 10:24 UTC, VadimZharkov approved these changes

2024-02-14 14:49 UTC, merged